### ISSUE TITLE
The time reported

### ISSUE THREAD

**Issue by youkaichao** [dbolya/parc#1]
Hi, I found that the running time is sometimes reported in milliseconds (e.g. Figure 2 (b)) and sometimes reported in seconds (Table 4). Are they consistent? Milliseconds and seconds are orders of magnitudes different.

**Comment by dbolya** [comment]
Ah oops, all timing is in ms, so the label of (s) in Table 4 is a mistake.

I'll keep note of this issue locally so we can fix it in a paper update later.
Thanks for pointing that out!
