### ISSUE TITLE
Problem of download datasets

### ISSUE THREAD

**Issue by yaolu-zjut** [dbolya/parc#2]
I have a problem downloading the probes.zip. The browser says I can't download the probes.zip, while I actually can download but can not obtain the final files. Errors occur at the last moment  when the download is complete. Could you please provide me with another link to download the file?

**Comment by dbolya** [comment]
Hi, do these links work for you?
Probes: https://www.dropbox.com/s/l08n4ejuip2b1h6/probes.zip?dl=0
Models: https://www.dropbox.com/s/gk32wdqmf19lnmt/models.zip?dl=0

**Comment by yaolu-zjut** [comment]
Thank you, I have solved this question.
