### ISSUE TITLE
train_test split

### ISSUE THREAD

**Issue by CuongNN218** [dbolya/parc#3]
Hi @dbolya ,
Thanks for your great work. I'm trying to do several experiments based on your code and found that the Caltech-101 train-test-split file do not exist. Can you share your train-test-split file of all datasets?

**Comment by dbolya** [comment]
Sure! I have provided the train_test_split and image to class mappings for the following datasets:
> CUB200
> NABird
> Caltech101

[train_test_splits.zip](https://github.com/dbolya/parc/files/9343880/train_test_splits.zip)

I believe these should be all of the datasets that use those, but let me know if I've missed any.
