### ISSUE TITLE
【pretrained_model & datasaet questions】

### ISSUE THREAD

**Issue by Fay-why** [dbolya/parc#5]
Hello, dear author! Thanks for your great job!

I am trying to reproduce your paper using your codes. But when I try to make `buget=1000`, I need to remake the forward embeddings. At this moment, I met two questions：

1. I have downloaded 6 datasets according to your codes and some others public sites. But when facing to `caltech101`, I try to download it from public link `https://data.caltech.edu/records/mzrjq-6wc02` ( Your code didn't have the URL about this dataset ). After  unzipping the dataset, I couldn't find the files which needed in your codes: `images.txt, image_class_labels.txt, train_test_split.txt`. Can you share this full  dataset with me ?
2. When I try to remake the forward embeddings using your public pretrained models, there is no
     `models/resnet50/resnet50_imagenet.pth`  in this model files. Can you share this model with me?

Hoping for your response!!

**Comment by dbolya** [comment]
Hi, no problem. There were some things left out from the initial release it seems.

1. The train-test splits are available in a prior issue: #3
2. This model seems to have been missed. I've made it available here:
https://drive.google.com/file/d/1VOFNa3v87T0kYzFklneqMC-YaVRNlPCs/view?usp=share_link

Let me know if these work for you.

**Comment by Fay-why** [comment]
> 
Thanks for your response.

1.  Actually, there is no `images.txt` file in this link, can you send the full file to me?
2. This model is worked for me !

Thanks again~

**Comment by dbolya** [comment]
Apologies for the delay. Turns out the dataset got deleted off our cluster, but I found a backup.

Here's the metadata for all 3 datasets that need it:
[metadata.zip](https://github.com/dbolya/parc/files/10394700/metadata.zip)

**Comment by Fay-why** [comment]
Thanks for your reply!
I have reproduce the `probes=1000` successfully according the above metadata.
Thanks for your help, I hope I can explore some new and useful stuff based on your work.
I will close this issue.
